### ISSUE TITLE
GUI improvements needed

### ISSUE THREAD

**Issue by SalehHub** [naifalshaye/laravelgui#1]
Hi Naif, thank you so much for this amazing project, I have some GUI related suggestions to improve this project:

1. Enable pasting text to text input boxes, **"laravel path"** for instance. it is really frustrating to type the path over and over again, or add the ability to pick the path using the **Folder Picker Window**
2. Add the ability to maximize the app window
3. Save laravel projects paths **locally** and show them in a **list** so we can just click on any path without having to type the path each time we want to switch to a different project.
4. We should be able to maximize the **output window** in home screen to have a better look of the output text or add the ability to **decrease the font size** ( Try to execute the `route:list ` command and you will get my point)
5. In the home screen switching **SSH Radio Button Mode** will cause the laravel path input to be emptied even if there are no SSH details in the setting screen.
6. The spinner loading indicator will continue showing even if the command failed to execute for any reason.

Thanks again.

**Comment by naifalshaye** [comment]
Hi Saleh, 
Thank you so much for your comments, I really appreciate it and I'll work on fixing them asap.

**Comment by naifalshaye** [comment]
Dear @salehahmedZ,

I didn't get this one:
5. In the home screen switching SSH Radio Button Mode will cause the laravel path input to be emptied even if there are no SSH details in the setting screen.

I clicked the ssh mode button where there are no ssh details in settings and the laravel path still there. Could you please explain more.

Thanks

**Comment by SalehHub** [comment]
I think at that time I didn’t "save" the path but rather just clicked "verify" that's why it disappeared when I tried to activate the SSH mode

**Comment by naifalshaye** [comment]
Got it, thanks

**Comment by aisthetes** [comment]
What is **Laravel path** for? I try to insert the path to the project (d:\_www\projectname) and nothing changes. Save button is not active. Over SSH work.

Windows 10 1809

**Comment by naifalshaye** [comment]
@salehahmedZ version 1.2 is released thanks for your suggestions.

@aisthetes issue has been solved in 1.2

you can download latest version now http://laravel-gui.io
